Product.destroy_all
Product.reset_pk_sequence

Product.create(
  category: 'Grips',
  brand: 'Fox',
  title: 'grip 1 test',
  description: 'lorem ipsum dolar',
  color1: 'Red',
  color2: 'Blue',
  color3: 'Green',
  color4: 'Yellow',
  color5: 'color5',
  size1: 'Small',
  size2: 'Medium',
  size3: 'Large',
  size4: 'size4',
  size5: 'size5',
  quantity: 50,
  price: 25.15,
  saleprice: '',
  image1: 'item2',
  image2: '',
  image3: '',
  image4: '',
  image5: '',
  review: '',
  rating: '',
  checkoutquantity: 1,
)

Product.create(
  category: 'Grips',
  brand: 'Fox',
  title: 'grip-2',
  description: 'lorem ipsum dolar',
  color1: 'color1',
  color2: 'color2',
  color3: 'color3',
  color4: 'color4',
  color5: 'color5',
  size1: 'size1',
  size2: 'size2',
  size3: 'size3',
  size4: 'size4',
  size5: 'size5',
  quantity: 50,
  price: 20.00,
  saleprice: '',
  image1: 'item2',
  image2: '',
  image3: '',
  image4: '',
  image5: '',
  review: '',
  rating: '',
  checkoutquantity: 1,
)

Product.create(
  category: 'Grips',
  brand: 'Fox',
  title: 'grip-3',
  description: 'lorem ipsum dolar',
  color1: 'color1',
  color2: 'color2',
  color3: 'color3',
  color4: 'color4',
  color5: 'color5',
  size1: 'size1',
  size2: 'size2',
  size3: 'size3',
  size4: 'size4',
  size5: 'size5',
  quantity: 50,
  price: 20.00,
  saleprice: '',
  image1: 'item2',
  image2: '',
  image3: '',
  image4: '',
  image5: '',
  review: '',
  rating: '',
  checkoutquantity: 1,
)

Product.create(
  category: 'Grips',
  brand: 'Fox',
  title: 'grip-4',
  description: 'lorem ipsum dolar',
  color1: 'color1',
  color2: 'color2',
  color3: 'color3',
  color4: 'color4',
  color5: 'color5',
  size1: 'size1',
  size2: 'size2',
  size3: 'size3',
  size4: 'size4',
  size5: 'size5',
  quantity: 50,
  price: 20.00,
  saleprice: '',
  image1: 'item2',
  image2: '',
  image3: '',
  image4: '',
  image5: '',
  review: '',
  rating: '',
  checkoutquantity: 1,
)

Product.create(
  category: 'Grips',
  brand: 'Fox',
  title: 'grip-5',
  description: 'lorem ipsum dolar',
  color1: 'color1',
  color2: 'color2',
  color3: 'color3',
  color4: 'color4',
  color5: 'color5',
  size1: 'size1',
  size2: 'size2',
  size3: 'size3',
  size4: 'size4',
  size5: 'size5',
  quantity: 50,
  price: 20.00,
  saleprice: '',
  image1: 'item2',
  image2: '',
  image3: '',
  image4: '',
  image5: '',
  review: '',
  rating: '',
  checkoutquantity: 1,
)

Product.create(
  category: 'Grips',
  brand: 'Colony',
  title: 'cgrip-1',
  description: 'lorem ipsum dolar',
  color1: 'color1',
  color2: 'color2',
  color3: 'color3',
  color4: 'color4',
  color5: 'color5',
  size1: 'size1',
  size2: 'size2',
  size3: 'size3',
  size4: 'size4',
  size5: 'size5',
  quantity: 50,
  price: 20.00,
  saleprice: '',
  image1: 'item2',
  image2: '',
  image3: '',
  image4: '',
  image5: '',
  review: '',
  rating: '',
  checkoutquantity: 1,
)

Product.create(
  category: 'Grips',
  brand: 'Colony',
  title: 'cgrip-2',
  description: 'lorem ipsum dolar',
  color1: 'color1',
  color2: 'color2',
  color3: 'color3',
  color4: 'color4',
  color5: 'color5',
  size1: 'size1',
  size2: 'size2',
  size3: 'size3',
  size4: 'size4',
  size5: 'size5',
  quantity: 50,
  price: 20.00,
  saleprice: '',
  image1: 'item2',
  image2: '',
  image3: '',
  image4: '',
  image5: '',
  review: '',
  rating: '',
  checkoutquantity: 1,
)

Product.create(
  category: 'Grips',
  brand: 'Colony',
  title: 'cgrip-3',
  description: 'lorem ipsum dolar',
  color1: 'color1',
  color2: 'color2',
  color3: 'color3',
  color4: 'color4',
  color5: 'color5',
  size1: 'size1',
  size2: 'size2',
  size3: 'size3',
  size4: 'size4',
  size5: 'size5',
  quantity: 50,
  price: 20.00,
  saleprice: '',
  image1: 'item2',
  image2: '',
  image3: '',
  image4: '',
  image5: '',
  review: '',
  rating: '',
  checkoutquantity: 1,
)

Product.create(
  category: 'Grips',
  brand: 'Colony',
  title: 'cgrip-4',
  description: 'lorem ipsum dolar',
  color1: 'color1',
  color2: 'color2',
  color3: 'color3',
  color4: 'color4',
  color5: 'color5',
  size1: 'size1',
  size2: 'size2',
  size3: 'size3',
  size4: 'size4',
  size5: 'size5',
  quantity: 50,
  price: 20.00,
  saleprice: '',
  image1: 'item2',
  image2: '',
  image3: '',
  image4: '',
  image5: '',
  review: '',
  rating: '',
  checkoutquantity: 1,
)

Product.create(
  category: 'Grips',
  brand: 'Colony',
  title: 'cgrip-5',
  description: 'lorem ipsum dolar',
  color1: 'color1',
  color2: 'color2',
  color3: 'color3',
  color4: 'color4',
  color5: 'color5',
  size1: 'size1',
  size2: 'size2',
  size3: 'size3',
  size4: 'size4',
  size5: 'size5',
  quantity: 50,
  price: 20.00,
  saleprice: '',
  image1: 'item2',
  image2: '',
  image3: '',
  image4: '',
  image5: '',
  review: '',
  rating: '',
  checkoutquantity: 1,
)

Product.create(
  category: 'Pedals',
  brand: 'Fox',
  title: 'pedal-1',
  description: 'lorem ipsum dolar',
  color1: 'color1',
  color2: 'color2',
  color3: 'color3',
  color4: 'color4',
  color5: 'color5',
  size1: 'size1',
  size2: 'size2',
  size3: 'size3',
  size4: 'size4',
  size5: 'size5',
  quantity: 50,
  price: 20.00,
  saleprice: '',
  image1: 'item1',
  image2: '',
  image3: '',
  image4: '',
  image5: '',
  review: '',
  rating: '',
  checkoutquantity: 1,
)

Product.create(
  category: 'Pedals',
  brand: 'Fox',
  title: 'pedal-2',
  description: 'lorem ipsum dolar',
  color1: 'color1',
  color2: 'color2',
  color3: 'color3',
  color4: 'color4',
  color5: 'color5',
  size1: 'size1',
  size2: 'size2',
  size3: 'size3',
  size4: 'size4',
  size5: 'size5',
  quantity: 50,
  price: 20.00,
  saleprice: '',
  image1: 'item1',
  image2: '',
  image3: '',
  image4: '',
  image5: '',
  review: '',
  rating: '',
  checkoutquantity: 1,
)

Product.create(
  category: 'Pedals',
  brand: 'Fox',
  title: 'pedal-3',
  description: 'lorem ipsum dolar',
  color1: 'color1',
  color2: 'color2',
  color3: 'color3',
  color4: 'color4',
  color5: 'color5',
  size1: 'size1',
  size2: 'size2',
  size3: 'size3',
  size4: 'size4',
  size5: 'size5',
  quantity: 50,
  price: 20.00,
  saleprice: '',
  image1: 'item1',
  image2: '',
  image3: '',
  image4: '',
  image5: '',
  review: '',
  rating: '',
  checkoutquantity: 1,
)

Product.create(
  category: 'Pedals',
  brand: 'Fox',
  title: 'pedal-1',
  description: 'lorem ipsum dolar',
  color1: 'color1',
  color2: 'color2',
  color3: 'color3',
  color4: 'color4',
  color5: 'color5',
  size1: 'size1',
  size2: 'size2',
  size3: 'size3',
  size4: 'size4',
  size5: 'size5',
  quantity: 50,
  price: 20.00,
  saleprice: '',
  image1: 'item1',
  image2: '',
  image3: '',
  image4: '',
  image5: '',
  review: '',
  rating: '',
  checkoutquantity: 1,
)
